param(
  [Parameter(Mandatory = $true)]
  [string] $HubResourceGroupName,

  [string] $HubDeploymentName = 'hub-network',

  [string] $Location = 'swedencentral',

  [string] $TemplateFile = (Join-Path $PSScriptRoot '..\modules\hub\main.bicep'),

  [string] $ParametersFile = (Join-Path $PSScriptRoot '..\examples\hub.main.bicepparam'),

  [string] $HubJumpAdminPassword = $env:HUB_JUMP_ADMIN_PASSWORD,

  [string] $HubPrivateDnsResourceGroupName = $HubResourceGroupName,

  [string] $OutputPath = (Join-Path $PSScriptRoot '..\.outputs\hub-network.env.ps1'),

  [string] $JsonOutputPath = (Join-Path $PSScriptRoot '..\.outputs\hub-network.outputs.json'),

  [switch] $SkipResourceGroupCreate
)

$ErrorActionPreference = 'Stop'

function Add-EnvironmentLine {
  param(
    [Parameter(Mandatory = $true)]
    [string] $Name,

    [AllowNull()]
    [string] $Value
  )

  $escapedValue = ([string] $Value) -replace "'", "''"
  Add-Content -Path $OutputPath -Value ('$env:' + $Name + " = '$escapedValue'")
}

$outputDirectory = Split-Path -Parent $OutputPath
$jsonOutputDirectory = Split-Path -Parent $JsonOutputPath
New-Item -ItemType Directory -Path $outputDirectory -Force | Out-Null
New-Item -ItemType Directory -Path $jsonOutputDirectory -Force | Out-Null

if (-not (Test-Path $TemplateFile)) {
  throw "Hub template file '$TemplateFile' was not found."
}

if (-not (Test-Path $ParametersFile)) {
  throw "Hub parameters file '$ParametersFile' was not found."
}

if ([string]::IsNullOrWhiteSpace($HubJumpAdminPassword) -or $HubJumpAdminPassword -eq 'Replace-With-Strong-Password-123!') {
  throw "Set HUB_JUMP_ADMIN_PASSWORD or pass -HubJumpAdminPassword before deploying the hub network."
}

$env:HUB_JUMP_ADMIN_PASSWORD = $HubJumpAdminPassword

$accountResult = @(az account show -o json 2>&1)
if ($LASTEXITCODE -ne 0) {
  throw "Could not read the current Azure subscription. Azure CLI returned: $($accountResult -join [Environment]::NewLine)"
}

$subscriptionId = ($accountResult -join [Environment]::NewLine | ConvertFrom-Json).id

if (-not $SkipResourceGroupCreate) {
  $resourceGroupResult = @(az group create `
    --name $HubResourceGroupName `
    --location $Location `
    -o none 2>&1)

  if ($LASTEXITCODE -ne 0) {
    throw "Could not create or update resource group '$HubResourceGroupName'. Azure CLI returned: $($resourceGroupResult -join [Environment]::NewLine)"
  }
}

Write-Host "Deploying hub network deployment '$HubDeploymentName' to resource group '$HubResourceGroupName'..."

$deploymentErrorFile = New-TemporaryFile
try {
  $deploymentResult = @(az deployment group create `
    --resource-group $HubResourceGroupName `
    --name $HubDeploymentName `
    --template-file $TemplateFile `
    --parameters $ParametersFile `
    --query properties.outputs `
    -o json 2> $deploymentErrorFile)
  $deploymentErrors = Get-Content -Path $deploymentErrorFile -Raw
} finally {
  Remove-Item -Path $deploymentErrorFile -Force -ErrorAction SilentlyContinue
}

if ($LASTEXITCODE -ne 0) {
  throw "Could not deploy hub network '$HubDeploymentName' in resource group '$HubResourceGroupName'. Azure CLI returned: $($deploymentErrors + ($deploymentResult -join [Environment]::NewLine))"
}

$outputs = $deploymentResult -join [Environment]::NewLine | ConvertFrom-Json

if (-not $outputs.hubVnetName.value -or -not $outputs.hubVnetId.value -or -not $outputs.privateDnsZoneIds.value) {
  throw "Deployment '$HubDeploymentName' in resource group '$HubResourceGroupName' does not contain the expected hub networking outputs."
}

$hubOutput = [ordered]@{
  hubSubscriptionId = $subscriptionId
  hubResourceGroupName = $HubResourceGroupName
  hubPrivateDnsResourceGroupName = $HubPrivateDnsResourceGroupName
  hubVnetName = $outputs.hubVnetName.value
  hubVnetId = $outputs.hubVnetId.value
  privateDnsZoneIds = [ordered]@{
    cognitiveServices = $outputs.privateDnsZoneIds.value.cognitiveServices
    openAi = $outputs.privateDnsZoneIds.value.openAi
    aiServices = $outputs.privateDnsZoneIds.value.aiServices
    blob = $outputs.privateDnsZoneIds.value.blob
    file = $outputs.privateDnsZoneIds.value.file
    cosmos = $outputs.privateDnsZoneIds.value.cosmos
    search = $outputs.privateDnsZoneIds.value.search
    keyVault = $outputs.privateDnsZoneIds.value.keyVault
    acr = $outputs.privateDnsZoneIds.value.acr
    appConfig = $outputs.privateDnsZoneIds.value.appConfig
    containerApps = $outputs.privateDnsZoneIds.value.containerApps
  }
}

$hubOutput | ConvertTo-Json -Depth 10 | Set-Content -Path $JsonOutputPath

Set-Content -Path $OutputPath -Value @(
  '# Generated by networking-example-remove/scripts/export-hub-outputs.ps1.'
  '# Dot-source this file before deploying spokes: . ./networking-example-remove/.outputs/hub-network.env.ps1'
  ''
)

Add-EnvironmentLine -Name 'HUB_SUBSCRIPTION_ID' -Value $hubOutput.hubSubscriptionId
Add-EnvironmentLine -Name 'HUB_RESOURCE_GROUP_NAME' -Value $hubOutput.hubResourceGroupName
Add-EnvironmentLine -Name 'HUB_PRIVATE_DNS_RESOURCE_GROUP_NAME' -Value $hubOutput.hubPrivateDnsResourceGroupName
Add-EnvironmentLine -Name 'HUB_VNET_NAME' -Value $hubOutput.hubVnetName
Add-EnvironmentLine -Name 'HUB_VNET_ID' -Value $hubOutput.hubVnetId
Add-EnvironmentLine -Name 'DNS_COGNITIVE_SERVICES_ID' -Value $hubOutput.privateDnsZoneIds.cognitiveServices
Add-EnvironmentLine -Name 'DNS_OPENAI_ID' -Value $hubOutput.privateDnsZoneIds.openAi
Add-EnvironmentLine -Name 'DNS_AI_SERVICES_ID' -Value $hubOutput.privateDnsZoneIds.aiServices
Add-EnvironmentLine -Name 'DNS_BLOB_ID' -Value $hubOutput.privateDnsZoneIds.blob
Add-EnvironmentLine -Name 'DNS_FILE_ID' -Value $hubOutput.privateDnsZoneIds.file
Add-EnvironmentLine -Name 'DNS_COSMOS_ID' -Value $hubOutput.privateDnsZoneIds.cosmos
Add-EnvironmentLine -Name 'DNS_SEARCH_ID' -Value $hubOutput.privateDnsZoneIds.search
Add-EnvironmentLine -Name 'DNS_KEYVAULT_ID' -Value $hubOutput.privateDnsZoneIds.keyVault
Add-EnvironmentLine -Name 'DNS_ACR_ID' -Value $hubOutput.privateDnsZoneIds.acr
Add-EnvironmentLine -Name 'DNS_APPCONFIG_ID' -Value $hubOutput.privateDnsZoneIds.appConfig
Add-EnvironmentLine -Name 'DNS_CONTAINERAPPS_ID' -Value $hubOutput.privateDnsZoneIds.containerApps

Write-Host "Wrote spoke environment file: $OutputPath"
Write-Host "Wrote hub outputs JSON file: $JsonOutputPath"
